[tool.mypy]
python_version = 3.12
exclude = [
    "venv",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
pythonpath = "src"
addopts = "--doctest-modules --cov"
log_cli="true"
log_level="DEBUG"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
